# Generated by Django 4.2.1 on 2023-05-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('1000 To 10000', '1000 To 10000'), ('10000 To 20000', '10000 To 20000'), ('20000 To 30000', '20000 To 30000'), ('30000 To 40000', '30000 To 40000')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.brands')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.categories')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.filter_price')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.warranty')),
            ],
        ),
    ]
